### ISSUE TITLE
Certz does not have counters per-profile

### ISSUE THREAD

**Issue by haussli** [openconfig/gnsi#111]
certz supports multiple ssl profiles (RotateCertificateRequest.ssl_profile_id).  It also maintains counters exposed as
augment /oc-sys:system/oc-sys-grpc:grpc-servers/oc-sys-grpc:grpc-server/oc-sys-grpc:state:

This structure does not appear to be per-ssl_profile_id.  So,
1) it is global, which is not logical given its fields, or
2) it needs a ssl_profile_id field and a list keyed by that id, in yang parlance.

2 seems to be the answer, but I'm not sure what implementation to suggest here.

**Comment by morrowc** [comment]
Sadly I keep avoiding learning much of anything about YANG.. but like a ton of other things on a network device where there are multiple instances of a thing, yea .. we want to count the relevant / critical bits related to those instances and not attempt to interpolate / infer what one instance of the thing is doing based on jiggery-pokery from remote.

so yea, please do 2 ... the path you point to doesn't look directly like it's 'ssl profile' related...

**Comment by haussli** [comment]
I think that having an ssl-profile-id associated with each grpc-server would solve this.  Would you create a MR for  that?
