### ISSUE TITLE
authz ProbeResponse action enum

### ISSUE THREAD

**Issue by LimeHat** [openconfig/gnsi#157]
Is it correct to assume that `ACTION_UNSPECIFIED` should never be returned in a `ProbeResponse` message?
I.e. it was added as an enum best practice and does not carry any logical meaning (such as an implicit "no match / deny" rule vs an explicit deny match for `ACTION_DENY`).

https://github.com/openconfig/gnsi/blob/26b2e73701d2ab86d87b169fbefe444c9b953543/authz/authz.proto#L226-L232

cc @morrowc @tomek-US

**Comment by morrowc** [comment]
that's certainly a best-practice looking thing, yes.
I suspect that in the world of AUTHz if you make a request you get a deny or permit there is no other answer... or 'another answer is a deeper error' :)
