### ISSUE TITLE
Support for RSA 3072 and ECDSA_P_384

### ISSUE THREAD

**Issue by rohit21187** [openconfig/gnsi#205]
Hi I see that in [gnsi/credentialz/credentialz.proto](https://github.com/openconfig/gnsi/blob/main/credentialz/credentialz.proto) the keyType supported are KEY_TYPE_ECDSA_P_256, KEY_TYPE_ECDSA_P_521, KEY_TYPE_ED25519,KEY_TYPE_RSA_2048, KEY_TYPE_RSA_4096.

Earlier there was no differentiation on the basis of bit size. This was brought in by @nmahabaleshwar [commit](https://github.com/openconfig/gnsi/commit/eb38162f1f5e5b36159a4f8810d98032f864fad8) for ecdsa. And then another commit by @marcushines [commit](https://github.com/openconfig/gnsi/pull/80/commits) that was for rsa key type for 4096 and 2048.

I believe we are still missing support for RSA 3072 and ECDSA_P_384.

**Comment by dplore** [comment]
Hi Rohit, Feel free to create a PR to add the additional keys.  We can
review and approve

**Comment by rohit21187** [comment]
Thanks Darren

**Comment by morrowc** [comment]
#206 was merged.
