### ISSUE TITLE
Clarify expectation of trust_bundle with regards to mTLS

### ISSUE THREAD

**Issue by RonanMacF** [openconfig/gnsi#44]
When confiuring an SSL proile on the switch for mTLS there is generally two thing in particular done

1. A particular CA is marked as trusted. This will be used to authenticate the clients certificate and does not necessarily have to be part of the server certificate chain.
2. A certificate chain is formed on the server with a leaf certificate and 0 or more intermediate certs.

The proto comments contains the following

```
// Target (as seen from gNSI.certificate microservice point of view)
// |
// +-+ certificate (used by all gRPC services)
// | +- certificate (with public key)
// | +- private key
// |
// +-+ trust bundle (Certificate Authority certificates)
// | +- CA Root certificate
// | +- CA Intermediate Certificate
```

This would indicate to me that all CA's as part of the trust bundle are only to be marked as trusted and the server will only have one certificate used in it's chain.

I think a reasonable change to this would be to change

```
  oneof entity {
    Certificate certificate = 3;
    CertificateBundle trust_bundle = 4;
    CertificateRevocationListBundle certificate_revocation_list_bundle = 5;
  }
```

to
```
  oneof entity {
    Certificate leaf_certificate = 3;
    CertificateBundle intermediate_certificates = 4;
    CertificateBundle trust_bundle = 5;
    CertificateRevocationListBundle certificate_revocation_list_bundle = 6;
  }
```

The private key would be optional for all certs in the chain except for the leaf certificate. This is already marked as optional so we are good here.

**Comment by marcushines** [comment]
@tomek-US 

I believe our view was the trust_bundle contains the CA root as well as all intermediates

I am not sure why we would seperate it out like this?

**Comment by RonanMacF** [comment]
It sounds like trust_bundle is the chain including the RootCA that created the leaf server certificate.

This means that there is no option to provide a distinct list of CA's that may have signed a client certificate which would be used in mTLS.

**Comment by tomek-US** [comment]
Yes, the assumption behind this API design decision is that the trust bundle includes the whole chain of CA certificates that are needed to verify the incoming connection from clients. It might be but does not have to be the one that is used to sign the servers certificate. The assumption is that when the server (host) certificate is provided using the Rotate() operation it is from a trusted source and there is no need to verify it.

**Comment by RonanMacF** [comment]
Understood, to a trust_bundle is a list of trusted certificates that the server can use to verify a client during mTLS.

The issue still stands with the client validating the server. The server must return its chain to the client, at the moment the message can only include the leaf certificate, but if there is an intermediate CA in the chain there is no way to provide this.

```
      ┌───►serverInterCA─────►serverLeaf
      │
rootCA│
      │
      │
      └───► clientInterCA────►clientLeaf
      
```

in this case the rootCA would be the trusted cert for the client and server, (trust_bundle). Ther client would give `clientInterCA` and `clientLeaf`. This would be validated by the server fine. The server _should_ give `serverInterCA` and `serverLeaf` to the client but the spec only allows for `serverLeaf` to be passed and therefore returned. It should not be the servers job to figure out what CA's in the trust bundle are also part of the servers chain by trying to validate it itself, instead the client should be able to be specific on what the servers chain is and what the trusted certs are.

**Comment by tomek-US** [comment]
Hmm. I guess I am missing something but to my best knowledge the server _does_ _not_ send the CA trust bundle to the client. The client has to have it locally and use it to verify the received server certificate.

Could you point me to some text describing the scenario with the server providing the CA?

**Comment by RonanMacF** [comment]
The server should not send the trusted certificates, but should send any intermediate CA that is part of its own chain. This may or may not include the root CA.

this is discussed here https://www.rfc-editor.org/rfc/rfc5246#section-7.4.2

**Comment by tomek-US** [comment]
OK. If I understood correctly a single leaf as a server certificate is not enough. Then making it a bundle should solve the problem, right?

```
  oneof entity {
    CertificateBundle certificate_bundle = 3;
    CertificateBundle trust_bundle = 4;
    CertificateRevocationListBundle certificate_revocation_list_bundle = 5;
  }
```

With this approach one can specify either a single/leaf server certificate or a chain of certificates that are needed by the client to verify that the server uses a valid certificate.

**Comment by RonanMacF** [comment]
That is correct. It should be clear that a private key is only needed on the leaf certificate and the leaf certificate should be clear, either first or last certificate.

**Comment by tomek-US** [comment]
I like the idea of introducing the concept of a parent in the chain of certificates. Both options look good to me.
