### ISSUE TITLE
Proposal to use the public key generated on the box for creating SSH host certificate

### ISSUE THREAD

**Issue by nmahabaleshwar** [openconfig/gnsi#58]
Some switches have the capability to generate private/public keys eliminating the necessity to generate them externally and transferring them to the switch. This avoids the potential security risk on transmitting private keys over the wire. Below is a proposal which helps operators utilize this capability.

Below will be the sequence of steps,
1. Query the key generation capability of the switch. This is basically providing a key specification and checking if the switch can generate the public/private key.

	`rpc CanGenerateKey(CanGenerateKeyRequest) returns (CanGenerateKeyResponse)`

2. Trigger generation of the key.

	`rpc GenerateKey(GenerateKeyRequest) returns (GenerateKeyResponse)`

3. Poll to check if the key generation is complete. Key generation takes time, hence we need to poll the switch for key generation. If the key is ready, the public key portion of it should be returned else a simple `Not ready`.

	`rpc GetPublicKey(GetPublicKeyRequest) returns (GetPublicKeyResponse)`

4. Sign the public key with the CA's private key and generate the host certificate.
5. Install the generated host certificate onto the switch.

	`rpc RotateHostCredentials(RotateHostCredentialsRequest) returns (RotateHostCredentialsResponse)`

This is an existing RPC, we can just use the existing message ServerKeysRequest. The public/private key portions of the message need not be set.

If the operator does not wish to use this capability or if the switch does not support this capability, we can directly go to Step 5 and install the externally generated keys and certificates using the existing RPC.

**Comment by tomek-US** [comment]
IMHO there is no need for additional RPCs (perhaps with exception of CanGenerateKey() but I would argue that it also can be part of RotateHostCredentials) - the GenerateKeyRequest/GenerateKeyResponse can be made part of the RotateHostCredentials streaming RPC.

In such case instead of sending ServerKeysRequest you would:
(1) send GenerateKeyRequest and
(2) wait for GenerateKeyResponse  that would contain the generated public key and then
(3) after signing it with CA the next message would be ServerKeysRequest with the signed certificate.

This approach has the advantage that it (1) allows for optionality - the client uses the same RPC but can chose the steps, (2) makes the process a transaction that can consist of rotation of all related credentials.

**Comment by nmahabaleshwar** [comment]
To align with Certz, we can have a separate RPC to query key generation capability and just new message in the existing Rotate RPC for triggering key generation and retrieve it. Below is the updated steps,

1. Query the key generation capability of the switch. This is basically providing a key specification and checking if the switch can generate the public/private key.

`rpc CanGenerateKey(CanGenerateKeyRequest) returns (CanGenerateKeyResponse)`

2. Trigger key generation and retrieve it. Note that key generation takes time for certain types of keys.

`rpc RotateHostCredentials(RotateHostCredentialsRequest) returns (RotateHostCredentialsResponse)`

`RotateHostCredentialsRequest` will have a new message type `GenerateKeyRequest` which will have the key specification.
`RotateHostCredentialsResponse` will have a new message type `GenerateKeyResponse` which will have the public key.

3. Sign the public key with the CA's private key and generate the host certificate.
4. Install the generated host certificate onto the switch.

`rpc RotateHostCredentials(RotateHostCredentialsRequest) returns (RotateHostCredentialsResponse)`

`RotateHostCredentialsRequest` will have the existing message type `ServersKeysRequest` which will have the signed SSH host certificate and optional public/private keys.

**Comment by tomek-US** [comment]
Sounds good!
