### ISSUE TITLE
Rotation of hostkeys/certificates using key generated on the switch

### ISSUE THREAD

**Issue by nmahabaleshwar** [openconfig/gnsi#78]
The current message `ServerKeysRequest` does not allow rotating and using a hostkey which has been generated on the switch. This is an important use case which was also present in the original specification. Hence we wanted to propose the below changes to the proto which allows setting both the ssh hostkeys and certificates in a consistent manner.

1. Change the name and contents of `GenerateKeysRequest` to the below since the message is no longer just instructing to trigger key generation on the switch.
```
message CreateKeysRequest {
    oneof req {
        KeyGen key_params = 1;
        bytes private_key = 2;
    }
}
```

2. Change the contents of `AuthenticationArtifacts` to the below
```
message AuthenticationArtifacts {
    oneof artifact {
        PublicKey hostkey_public_key = 1;
        bytes certificate = 2;
    }
}
```

Below will be the new workflow for the different scenarios

## Rotation of ssh host keys using externally generated keys

1. Client sends `CreateKeysRequest` with the desired private key. Server replies back with `CreateKeysResponse` which has the public key corresponding to the private key.
```
stream.Send(
    RotateHostCredentialsRequest {
        create_key_request: CreateKeysRequest {
            private_key: "A....=",
        }
    }
)
```

2. Client sends `AuthenticationArtifacts` with the public key which was received in the previous step. This will add the hostkey to config.

```
stream.Send(
    RotateHostCredentialsRequest {
        server_keys: ServerKeysRequest {
            auth_artifacts: AuthenticationArtifacts {
                hostkey_public_key: "A....=";
            }
            version: "v1.0",
            created_on: 3214451134,
        }
    }
)
```

## Rotation of ssh host keys using keys generated on the switch

1. Client sends `CreateKeysRequest` with the key specification. Server generates the key and replies back with `CreateKeysResponse` which has the public key corresponding to the generated private key.
```
stream.Send(
    RotateHostCredentialsRequest {
        create_key_request: CreateKeysRequest {
            key_params: KEY_GEN_SSH_KEY_TYPE_RSA_2048,
        }
    }
)
```

2. Client sends `AuthenticationArtifacts` with the public key which was received in the previous step. This will add the hostkey to config.

```
stream.Send(
    RotateHostCredentialsRequest {
        server_keys: ServerKeysRequest {
            auth_artifacts: AuthenticationArtifacts {
                hostkey_public_key: "A....=";
            }
            version: "v1.0",
            created_on: 3214451134,
        }
    }
)
```

## Rotation of ssh host keys and certificates using using externally generated keys

1. Client sends `CreateKeysRequest` with the desired private key. Server replies back with `CreateKeysResponse` which has the public key corresponding to the private key.
```
stream.Send(
    RotateHostCredentialsRequest {
        create_key_request: CreateKeysRequest {
            private_key: "A....=",
        }
    }
)
```

2. Client generates a certificate using the public key and sends `AuthenticationArtifacts` with the certificate. This will add the hostkey and certificate to config as an atomic operation.

```
stream.Send(
    RotateHostCredentialsRequest {
        server_keys: ServerKeysRequest {
            auth_artifacts: AuthenticationArtifacts {
                certificate: "A....=";
            }
            version: "v1.0",
            created_on: 3214451134,
        }
    }
)
```

## Rotation of ssh host keys and certificates using keys generated on the switch

1. Client sends `CreateKeysRequest` with the key specification. Server generates the key and replies back with `CreateKeysResponse` which has the public key corresponding to the generated private key.
```
stream.Send(
    RotateHostCredentialsRequest {
        create_key_request: CreateKeysRequest {
            key_params: KEY_GEN_SSH_KEY_TYPE_RSA_2048,
        }
    }
)
```

2. Client generates a certificate using the public key and sends `AuthenticationArtifacts` with the certificate. This will add the hostkey and certificate to config as an atomic operation.

```
stream.Send(
    RotateHostCredentialsRequest {
        server_keys: ServerKeysRequest {
            auth_artifacts: AuthenticationArtifacts {
                certificate: "A....=";
            }
            version: "v1.0",
            created_on: 3214451134,
        }
    }
)
```

**Comment by tomek-US** [comment]
Perhaps I am missing something but I do not see a benefit of providing a private key, getting public key (as it will be returned in response) and then sending the public key back with (or without) a signed certificate.

As far as I understand the shortcomings of the existing API, what is needed is a context (a unique identifier) that is provided as an parameter of the `GenerateKeyRequest` and that is then used again in the `AuthenticationArtifacts`.

**Comment by tomek-US** [comment]
The context can also be the type of the key as this is the only parameter passed in the `GenerateKeyRequest`. This has the advantage of specifying which key/certificate is going to be replaced.

**Comment by nmahabaleshwar** [comment]
We are fine with using the `KeyType` enum which can point to a specific key type in `AuthenticationArtifacts` message. The message will be,

```
message AuthenticationArtifacts {
    oneof artifact {
        KeyType key_type = 1;
        bytes certificate = 2;
    }
}
```

We still think its good to have 2 messages sent to the server in all scenarios (key generated internally vs externally) which results in a uniform workflow.

**Comment by tomek-US** [comment]
Per my understanding we have the following use-cases:

1. no-certificate; priv+pub keys are generated on the switch
2. no-certificate; priv+pub keys are provided from outside
3. with-certificate; priv+pub keys are generated on the switch; certificate is signed outside
4. with-certificate; priv+pub keys and the certificate are provided from outside

Each of the use-cases has the additional dimension of encryption key type as the OpenSSH server can handle multiple encryption types at the same time.

Moreover, the public key does not have to be provided as it can be generated from the private key.

Taking all this into account I believe the following is needed to satisfy above mentioned use-cases:

1. `GenerateKeysRequest` with `KeyGen` specified. (no change necessary)
2. `ServerKeysRequest` with `private_key` and `KeyGen` specified. (`KeyGen key_type` has to be added to specify what priv+pub keypair is being rotated)
3. `GenerateKeysRequest` with `KeyGen` specified. (no change necessary) followed by `ServerKeysRequest` with `certificate` and `KeyGen` specified. (`KeyGen key_type` has to be added to specify what priv+pub keypair is being rotated)
4. `ServerKeysRequest` with `private_key`, `certificate` and `KeyGen` specified. (`KeyGen key_type` has to be added to specify what priv+pub keypair is being rotated)

It seems to me that the only change needed is to add `KeyGen key_type`  to `ServerKeysRequest` to cover all use-cases and to preserve the atomicity and clarity of the changes (minimum number of messages to achieve the required result).

Did I miss anything?

**Comment by nmahabaleshwar** [comment]
After our last discussion below is the updated proposal.

`GenerateKeysRequest` message will be used not only to instruct the switch to generate a key but also to add the generated key as the hostkey. When this message is received if any host certificate was installed, it will be removed from config. This message will be used to rotate ONLY the hostkey with a key generated on the switch. With this we don't need any changes to the existing messages.

Below are the different workflows,

## Rotation of ssh host keys using externally generated keys

1. Client sends `ServerKeysRequest` with the private key which is externally generated. This will add the provided key as the host key to config. If any host certificate was installed, it will be removed from config.

```
stream.Send(
    RotateHostCredentialsRequest {
        server_keys: ServerKeysRequest {
            auth_artifacts: AuthenticationArtifacts {
                private_key: "A....=";
            }
            version: "v1.0",
            created_on: 3214451134,
        }
    }
)
```

## Rotation of ssh host keys using keys generated on the switch

1. Client sends `GenerateKeysRequest` with the key specification. Server generates the key and replies back with `GenerateKeysResponse` which has the public key corresponding to the generated private key (this can be ignored by the client). The generated key is also added as the hostkey for the switch. If any host certificate was installed, it will be removed from config.

```
stream.Send(
    RotateHostCredentialsRequest {
        generate_key_request: GenerateKeysRequest {
            key_params: KEY_GEN_SSH_KEY_TYPE_RSA_2048,
        }
    }
)
```

Note: In the current proto format, only one key generated on the switch can be added to config.

## Rotation of ssh host keys and certificates using externally generated keys

1. Client sends `ServerKeysRequest` with the private key and certificate which are externally generated. This will add the provided key and certificate as the host key and host certificate to the config.

```
stream.Send(
    RotateHostCredentialsRequest {
        server_keys: ServerKeysRequest {
            auth_artifacts: AuthenticationArtifacts {
                private_key: "A....=";
                certificate: "A.....=";
            }
            version: "v1.0",
            created_on: 3214451134,
        }
    }
)
```

## Rotation of ssh host keys and certificates using keys generated on the switch

1. Client sends `GenerateKeysRequest` with the key specification. Server generates the key and replies back with `GenerateKeysResponse` which has the public key corresponding to the generated private key (this will be used to create an SSH certificate). The generated key is also added as the hostkey for the switch. If any host certificate was installed, it will be removed from config. At this point the switch is downgraded to authenticate using ONLY the host key until the certificate is installed using the `ServerKeysRequest` message.

```
stream.Send(
    RotateHostCredentialsRequest {
        generate_key_request: GenerateKeysRequest {
            key_params: KEY_GEN_SSH_KEY_TYPE_RSA_2048,
        }
    }
)
```

2. Client sends `ServerKeysRequest` with the certificate which is externally generated (using the public key which was received in the previous step). This will add the provided certificate as the host certificate to the config.

```
stream.Send(
    RotateHostCredentialsRequest {
        server_keys: ServerKeysRequest {
            auth_artifacts: AuthenticationArtifacts {
                certificate: "A.....=";
            }
            version: "v1.0",
            created_on: 3214451134,
        }
    }
)
```

If the Finalize message is not received, the config is rolled back to the state which was prior to the start of `RotateHostCredentialsRequest` RPC.

**Comment by erahn** [comment]
Niranjan, thanks for writing this up. Proposed edits below:

# Intro

> When this message is received if any host certificate was installed, it will be removed from config. 

s/it/the old host certificate/

> This message will be used to rotate ONLY the hostkey with a key generated on the switch.

s/used to rotate ONLY/used to update/

# Rotation of ssh host keys using keys generated on the switch

> Note: In the current proto format, only one key generated on the switch can be added to config.

Can you update the proposal to make this a `repeated` and allow for multiple hostkey algorithms to be rotated? That would make it in-line with the behavior for AuthenticationArtifacts: https://github.com/openconfig/gnsi/blob/6acb1b496c2057d9c61d3f6d96e35e699edab7f4/credentialz/credentialz.proto#L671

# Rotation of ssh host keys and certificates using externally generated keys

I would specify here that it is an error if the public key of the certificate does not correspond to the private key provided.

# Rotation of ssh host keys and certificates using keys generated on the switch

I would specify here that it is an error if the public key of the certificate does not correspond to the current active hostkey.

# Overall

We'd talked about making this a part of the documentation and I want to make sure that it is clear - this will be added in the appropriate section as documentation on how this is intended to work and how to handle each workflow.

**Comment by nmahabaleshwar** [comment]
Thanks for the comments Ethan, I have incorporated your comments and raised the PR https://github.com/openconfig/gnsi/pull/82

**Comment by nmahabaleshwar** [comment]
Closing this since https://github.com/openconfig/gnsi/pull/80 has merged
