### ISSUE TITLE
Description for gnsi.accounting.CommandService.cmd and cmd_args seem too vague

### ISSUE THREAD

**Issue by haussli** [openconfig/gnsi#95]
The description of CommandService.cmd and cmd_args seem too vague here:
https://github.com/openconfig/gnsi/blob/main/accounting/acct.proto#L147-L151

Like TACACS+ & RADIUS, the accounting should be the fully expanded command and its arguments.  eg: if a user enters
"sh ver det"
this would be expanded to
"show version detail"

How are arguments split?  is a '|'  or other punctuation handled specially?

Would there be special handling for the types in https://github.com/openconfig/gnsi/pull/94 ?

Vague documentation leads to variations in implementations and unnecessary document searching that are annoyances to operators and implementers, imiho.

**Comment by morrowc** [comment]
it'd be good to clean up the comments/documentation, yes!
do you want to send a PR for that?

**Comment by haussli** [comment]
For shell & cli: https://github.com/openconfig/gnsi/pull/107

The others need more thought/investigation.  I suspect http is the same, but I do not know what is typical for the others.
